#!/bin/bash

# the archive of the post-install scripts
POST_ARCH=post_install.tar.bz2
POST_SERV="https://deploy.flyingseagull.de/assets/$POST_ARCH"
POST_DIR=~/post_install

# get and extract the post-install scripts
wget --no-check-certificate $POST_SERV
tar xjvf $POST_ARCH
rm -rf $POST_ARCH

# TODO: sign the releases so we can make sure ppl don't put malicious code
# in our deployment scripts

shopt -s extglob
for post_install in $POST_DIR/+(S[0-9][0-9]*[^~]) ; do
  bash $post_install
done

# remove the temporary files
# rm -rf $POST_DIR
