#!/bin/sh


###
# HOSTAP settings
# allow hostapd to launch automaticall
#
HOSTAP_DEFAULT=/etc/default/hostapd
# don't enable hostap by default
# sed -i -e 's/#RUN_DAEMON="yes"/RUN_DAEMON="yes"/' $HOSTAP_DEFAULT
# perl -i -pe 's/^#DAEMON_CONF/DAEMON_CONF/' $HOSTAP_DEFAULT

echo 'protonet' > /etc/hostname
perl -i -pe "s/`uname -n`/protonet/" /etc/motd
# replace second line of hosts with 127.0.0.1 protonet
perl -i -ple '$_ = "127.0.0.1 protonet" if $. == 2 ; close ARGV if eof' /etc/hosts
# regenerate host ssh keys
rm /etc/ssh/ssh_host*
dpkg-reconfigure openssh-server

perl -i -pe "s/#dhcp-range=192.168.0.50,192.168.0.150,255.255.255.0,12h/dhcp-range=10.42.2.50,10.42.2.150,255.255.255.0,12h/" /etc/dnsmasq.conf
# backup default config
cp /etc/hostapd/hostapd.conf /etc/hostapd/hostapd.conf.orig

echo 'interface=ath0
bridge=br.eth1
driver=madwifi
logger_syslog=-1
logger_syslog_level=2
logger_stdout=-1
logger_stdout_level=2
debug=0
dump_file=/tmp/hostapd.dump
ctrl_interface=/var/run/hostapd
ctrl_interface_group=0
ssid=protonet
auth_algs=3
eapol_key_index_workaround=0
eap_server=0
wpa=3
wpa_key_mgmt=WPA-PSK
wpa_pairwise=TKIP CCMP
wpa_passphrase=helloworld' > /etc/hostapd/hostapd.conf


echo '# trusted interface
auto ath0
iface ath0 inet static
        # ensure ath0 is down (never fails because of "true")
        pre-up wlanconfig ath0 destroy || true
        # set up the ath0 device in AP mode before bringing up the interface (unless youre using AutoCreate)
        pre-up wlanconfig ath0 create wlandev wifi0 wlanmode ap
        # remove the ath0 device when bringing the interface down
        post-down wlanconfig ath0 destroy
        # now the address infos
        address 10.42.2.1
        netmask 255.255.255.0
        broadcast 10.42.2.255
        wireless-essid priv-protonet-1
        wireless-mode master
        wireless-key f2d6200dd9 # well, not really, use yours.

# guest interface
auto ath1
iface ath1 inet static
        # ensure ath1 is down (never fails because of "true")
        pre-up wlanconfig ath1 destroy || true
        # set up the ath1 device in AP mode before bringing up the interface (unless youre using AutoCreate)
        pre-up wlanconfig ath1 create wlandev wifi0 wlanmode ap
        # remove the ath1 device when bringing the interface down
        post-down wlanconfig ath1 destroy
        # now the address infos
        address 10.42.1.1
        netmask 255.255.255.0
        broadcast 10.42.1.255
        wireless-essid free-protonet-1
        wireless-mode master

        # wireless-key 1223-1234-1234-1234 # well, not really, use yours.' >> /etc/network/interfaces
        
echo 'options ath_pci autocreate=none' >> /etc/modprobe.d/options

