#!/bin/sh


#  taken from http://ubuntuforums.org/showthread.php?t=249889


sudo apt-get install nfs-kernel-server nfs-common portmap
# todo nex step is interactive, fix this
# When configuring portmap do =not= bind loopback. If you do you can either edit /etc/default/portmap by hand or run:
sudo dpkg-reconfigure portmap
sudo /etc/init.d/portmap restart

# sudo vim /etc/exports
# and add shares
# examples
# /home 192.168.0.0/255.255.255.0(rw,async,insecure,all_squash,anonuid =1000,anongid=1000) # insecure is for os x
# /files 192.168.1.0/24(rw,no_root_squash,async)

# sudo /etc/init.d/nfs-kernel-server restart
# sudo exportfs -a


#  bonjour
sudo apt-get install avahi-daemon


# /etc/avahi/services/nfs_export.service
# 
# <?xml version="1.0" standalone='no'?>
# <!DOCTYPE service-group SYSTEM "avahi-service.dtd">
# <service-group>
# <name replace-wildcards="yes">Export</name> ## Name
# <service>
# <type>_nfs._tcp</type>
# <port>2049</port>
# <txt-record>path=/media/md0/export</txt-record> ## path to shared Folder
# </service>
# </service-group>

# sudo /etc/init.d/avahi-daemon restart