#!/bin/sh

# MONIT INSTALLATION FOR TRACKING SERVICES AND ALL

sudo aptitude install monit

# also add this line:
#  include /etc/monit/monit_ptn_node
# TODO prepare base monit fileto include that line

# Afterwards we edit /etc/default/monit to enable the monit daemon. Change startup to 1 and set CHECK_INTERVALS to the interval in seconds that you would like monit to check your system:
# vim /etc/default/monit 
# Defaults for monit initscript
# sourced by /etc/init.d/monit
# installed at /etc/default/monit by maintainer scripts
# Fredrik Steen <stone@debian.org>

# You must set this variable to for monit to start
# startup=1

# To change the intervals which monit should run uncomment
# and change this variable.
# CHECK_INTERVALS=60
# Finally, we can start monit:
# /etc/init.d/monit start