#!/bin/sh

apt-get install darkstat

echo '# Turn this to yes when you have configured the options below.
START_DARKSTAT=yes

# You must set this option, else darkstat may not listen to
# the interface you want
INTERFACE="-i ath0"

PORT="-p 8888"
#BINDIP="-b 127.0.0.1"
#LOCAL="-l 10.1.1.0/24"
#FIP="-f 127.0.0.1"
#DNS="-n"
#SPY="--spy eth1"' > /etc/darkstat/init.cfg
