#!/bin/sh

# install git
apt-get -y install git-core
# clear path name list
hash -r

# lot of this comes from the fiveruns blog
# check for prerequisites
apt-get -y install build-essential libssl-dev libreadline5-dev zlib1g-dev

# get and build ruby
RUBY="ruby-1.8.6-p287" 
wget ftp://ftp.ruby-lang.org/pub/ruby/1.8/$RUBY.tar.gz
tar xzf $RUBY.tar.gz
rm $RUBY.tar.gz
cd $RUBY
./configure --prefix=/usr/local --with-openssl-dir=/usr --with-readline-dir=/usr --with-zlib-dir=/usr
make && make install && make install-doc
cd ..
rm -rf $RUBY

# now to rubygems
RUBYGEMS="rubygems-1.3.5" 
tar xzf $RUBYGEMS.tgz
rm $RUBYGEMS.tgz
cd $RUBYGEMS
/usr/local/bin/ruby setup.rb
cd ..
rm -rf $RUBYGEMS

# how about a webserver ;)
apt-get -y install apache2 apache2-threaded-dev

# getting the db
apt-get -y install sqlite3 libsqlite3-dev

# add github as source
gem sources -a http://gems.github.com

# installing the apps gems
sudo gem install jeremymcanally-context faker random_data mocha configatron sprockets ruby-debug

sudo gem install passenger

# todo: add later or something similar, this is interactive
# sudo passenger-install-apache2-module

# todo: add the following to apache config: /etc/apache2/conf.d/passenger.conf
# LoadModule passenger_module /usr/local/lib/ruby/gems/1.8/gems/passenger-2.2.4/ext/apache2/mod_passenger.so
# PassengerRoot /usr/local/lib/ruby/gems/1.8/gems/passenger-2.2.4
# PassengerRuby /usr/local/bin/ruby

# todo: mv /etc/apache2/sites-available/default to /etc/apache2/sites-available/_default
# todo: add the following to apache config : /etc/apache2/sites-available/default
# <VirtualHost *:80>
#    ServerName protonet
#    DocumentRoot /home/protonet/dashboard/public
# </VirtualHost>

