#!/bin/sh

# install git
apt-get -y install git-core
# clear path name list
hash -r

# lot of this comes from the fiveruns blog
# check for prerequisites
apt-get -y install build-essential libssl-dev libreadline5-dev zlib1g-dev

# get and build ruby
RUBY="ruby-1.8.6-p287" 
wget ftp://ftp.ruby-lang.org/pub/ruby/1.8/$RUBY.tar.gz
tar xzf $RUBY.tar.gz
rm $RUBY.tar.gz
cd $RUBY
./configure --prefix=/usr/local --with-openssl-dir=/usr --with-readline-dir=/usr --with-zlib-dir=/usr
make && make install && make install-doc
cd ..
rm -rf $RUBY

# now to rubygems
RUBYGEMS="rubygems-1.3.2" 
wget http://rubyforge.iasi.roedu.net/files/rubygems/$RUBYGEMS.tgz
tar xzf $RUBYGEMS.tgz
rm $RUBYGEMS.tgz
cd $RUBYGEMS
/usr/local/bin/ruby setup.rb
cd ..
rm -rf $RUBYGEMS

# how about a webserver ;)
apt-get -y install apache2

# getting the db
apt-get -y install sqlite3 libsqlite3-dev

# install merb
/usr/local/bin/gem install merb
