#!/bin/sh

# getting rabbitmq to run:
sudo apt-get -y install erlang
# sudo apt-get -y install erlang erlang-dev erlang-nox erlang-base libsctp1 unixodbc libltdl3 odbcinst1debian1
wget http://www.rabbitmq.com/releases/rabbitmq-server/v1.5.1/rabbitmq-server_1.5.1-1_all.deb
sudo dpkg --install rabbitmq-server_1.5.1-1_all.deb
rm rabbitmq-server_1.5.1-1_all.deb
# done, now to to the app

# problems? check for existing /var/lib/rabbitmq and delete