#!/bin/sh

# FIXME REVIEW THIS!! IT IS NOT NEEDED ANYMORE!

# the archive of the dashboard application
# POST_ARCH=dashboard_app.tar.bz2
# POST_SERV="http://protodeploy/$POST_ARCH"
# POST_DIR=~/dashboard

# get and extract the dashboard app
# wget --no-check-certificate $POST_SERV
# tar xjvf $POST_ARCH ./dashboard
# rm -rf $POST_ARCH


# todo: need to install app gems
# rake gems:install

# todo: need to create the production db
# RAILS_ENV=production rake db:create

# todo: restart the app if needed

# todo: rabbitmq should have been started already now start the dispatching server in the production env
# RAILS_ENV=production messaging/event_machine/js_dispatching_server.rb