#!/bin/sh

apt-get -y install build-essential

cp n2n.rb /usr/bin/n2n
chmod +x /usr/bin/n2n
wget http://protodeploy/n2n.tar.bz2
tar xjvf n2n.tar.bz2
cd n2n
make
make install
cd ..
rm -rf n2n

echo '#!/bin/sh

PATH=/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

PATH=/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

edge -f -a 10.0.0.4 -k encryptme -c mynetwork -l flyingseagull.de:1099' > /etc/init.d/n2n

# FIXME get the ip dynamically
# /usr/bin/n2n list' > /etc/init.d/n2n

chmod +x /etc/init.d/n2n
# add the startup script to the autostart
update-rc.d n2n defaults
