#!/bin/sh

apt-get -y install build-essential

cp n2n.rb /usr/bin/n2n
chmod +x /usr/bin/n2n
wget http://protodeploy/n2n.tar.bz2
tar xjvf n2n.tar.bz2
cd n2n
make
make install
cd ..
rm -rf n2n

echo '#!/bin/sh

PATH=/usr/sbin:/usr/bin:/sbin:/bin

/usr/bin/n2n list' > /etc/init.d/n2n

chmod +x /etc/init.d/n2n
# add the startup script to the autostart
update-rc.d n2n defaults
