#!/bin/sh


echo 'protonet' > /etc/hostname
perl -i -pe "s/`uname -n`/protonet/" /etc/motd
# replace second line of hosts with 127.0.0.1 protonet
perl -i -ple '$_ = "127.0.0.1 protonet" if $. == 2 ; close ARGV if eof' /etc/hosts
# regenerate host ssh keys
rm /etc/ssh/ssh_host*
dpkg-reconfigure openssh-server
