#!/bin/sh

apt-get -y install erlang
wget http://www.rabbitmq.com/releases/rabbitmq-server/v1.5.1/rabbitmq-server_1.5.1-1_all.deb
dpkg --install rabbitmq-server_1.5.1-1_all.deb
rm rabbitmq-server_1.5.1-1_all.deb