#!/bin/sh

# the archive of the dashboard application
POST_ARCH=dashboard_app.tar.bz2
POST_SERV="https://deploy.flyingseagull.de/assets/$POST_ARCH"
POST_DIR=~/dashboard

# get and extract the dashboard app
wget --no-check-certificate $POST_SERV
tar xjvf $POST_ARCH
