#!/bin/bash

# needed for ftp downloads
export ftp_proxy=http://protodeploy:3128/

# the archive of the post-install scripts
POST_ARCH=post_install.tar.bz2
POST_SERV="http://protodeploy/$POST_ARCH"
POST_DIR=~/post_install

# get and extract the post-install scripts
wget --no-check-certificate $POST_SERV
tar xjvf $POST_ARCH
rm -rf $POST_ARCH

# TODO: sign the releases so we can make sure ppl don't put malicious code
# in our deployment scripts

shopt -s extglob
cd $POST_DIR
for post_install in +(S[0-9][0-9]*[^~]) ; do
  chmod +x $post_install
  . $post_install
done

# remove the temporary files
# rm -rf $POST_DIR

# added to remove proxy from apt after installation
# should do the same as if you would set: 
# Acquire::http::Proxy "false";
# in that file
echo '' > /etc/apt/apt.conf

